name: user_repository
description: Dart package which manages the user domain.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.0
  uuid: ^3.0.0
  firebase_auth: ^5.4.0
  firebase_storage: ^12.3.7
  firebase_messaging: ^15.1.6
  firebase_core: ^3.9.0
  cloud_firestore: ^5.6.0