// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ-eJVR5Hv7ElBTeVNy8F3NjOii5345ig',
    appId: '1:83780161459:web:4749cd92bc3ede4f8005c6',
    messagingSenderId: '83780161459',
    projectId: 'projectenergy-85a9b',
    authDomain: 'projectenergy-85a9b.firebaseapp.com',
    storageBucket: 'projectenergy-85a9b.firebasestorage.app',
    measurementId: 'G-KHNE7V0TQR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9dzSI7e2UmxOZY-FkO4m71ytucxss9X0',
    appId: '1:83780161459:android:03eafdf6b1f4cdaf8005c6',
    messagingSenderId: '83780161459',
    projectId: 'projectenergy-85a9b',
    storageBucket: 'projectenergy-85a9b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUNI3lBegV6d0sufsItPo8d4HwCCJbXA8',
    appId: '1:83780161459:ios:b459c1365c1d0d1e8005c6',
    messagingSenderId: '83780161459',
    projectId: 'projectenergy-85a9b',
    storageBucket: 'projectenergy-85a9b.firebasestorage.app',
    iosBundleId: 'com.example.projectEnergy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUNI3lBegV6d0sufsItPo8d4HwCCJbXA8',
    appId: '1:83780161459:ios:b459c1365c1d0d1e8005c6',
    messagingSenderId: '83780161459',
    projectId: 'projectenergy-85a9b',
    storageBucket: 'projectenergy-85a9b.firebasestorage.app',
    iosBundleId: 'com.example.projectEnergy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQ-eJVR5Hv7ElBTeVNy8F3NjOii5345ig',
    appId: '1:83780161459:web:c2cf6f5df8cd3d8d8005c6',
    messagingSenderId: '83780161459',
    projectId: 'projectenergy-85a9b',
    authDomain: 'projectenergy-85a9b.firebaseapp.com',
    storageBucket: 'projectenergy-85a9b.firebasestorage.app',
    measurementId: 'G-DS08QQ456V',
  );
}
